#!/bin/bash
COMMAND=0
SCRIPT=$0
INSTALLPATH=/usr/local/advtty
DEAMON=advttyd
SERVICE=vcomd
DRIVER=advvcom
CONFIGFILE=$INSTALLPATH/advttyd.conf
DEAMONFILE=$INSTALLPATH/$DEAMON
UPGRADEPATH=/tmp/__advvcom_upgrade__
#DKMSFILE=/lib/modules/$(uname -r)/updates/dkms/$DRIVER.ko
KERNEL=$(uname -r|cut -c1-3)
if [ $KERNEL = "2.4" ] 
then
DRIVERFILE=$INSTALLPATH/$DRIVER.o
else
DRIVERFILE=$INSTALLPATH/$DRIVER.ko
fi
UPGRADEOPT=()

RETURN=
OBJECTIVE=

hasdriver()
{
	COUNT=$(lsmod | grep $DRIVER -c)
	if [ $COUNT -gt 0 ]
	then
		echo "kernel moduel $DRIVER.ko detected..."
		RETURN=1
	else
		echo "kernel moduel $DRIVER.ko not installed... try objective \"insert\" first"
		RETURN=0
	fi
}

insdriver()
{
	if [ $KERNEL = "2.4" ] 
	then
	echo "inserting kernel moduel $DRIVER.o ..."
	insmod $DRIVERFILE
	elif [ -e $DRIVERFILE ]
	then
	echo "inserting kernel module $DRIVER.ko ..."
	insmod $DRIVERFILE
	else
	echo "inserting DKMS moduel $DRIVER ..."
	modprobe $DRIVER
	fi
}

rmdriver()
{
	if [ $KERNEL = "2.4" ] 
	then
	echo "removing kernel moduel $DRIVER..."
	rmmod $DRIVER
	else
	echo "removing kernel moduel $DRIVER.ko..."
	rmmod $DRIVER.ko
	fi
}

stopService()
{
	echo "stoping all local services..."
	killall -s 9 $SERVICE
}

startDeamon()
{
	# for 2.4.x kernel, we should make node by myself
	if [ $KERNEL = "2.4" ] 
	then
		i=1
		while [[ $i -le 256 ]]
		do
			if [ -z $(awk '$2=="vttyAP"{print $1}' /proc/devices) ]
			then
				mknod /dev/vttyAP$i c $(awk '$2=="vttyap/%d"{print $1}' /proc/devices) $i
			else			
				mknod /dev/vttyAP$i c $(awk '$2=="vttyAP"{print $1}' /proc/devices) $i
			fi			
			((i = i + 1))
		done
	fi
	echo "invoking local deamon..."
	install -m 777 -d /tmp/advmon
	$DEAMONFILE -d -w ${INSTALLPATH}

}

syncDeamon()
{
	# for 2.4.x kernel, we should make node by myself
	if [ $KERNEL = "2.4" ] 
	then
		i=1
		while [[ $i -le 256 ]]
		do
			if [ -z $(awk '$2=="vttyAP"{print $1}' /proc/devices) ]
			then
				mknod /dev/vttyAP$i c $(awk '$2=="vttyap/%d"{print $1}' /proc/devices) $i
			else			
				mknod /dev/vttyAP$i c $(awk '$2=="vttyAP"{print $1}' /proc/devices) $i
			fi			
			((i = i + 1))
		done
	fi
	echo "synchronizing local deamon..."
	install -m 777 -d /tmp/advmon
	$DEAMONFILE -d -w ${INSTALLPATH} -c

}


stopDeamon()
{
#	killall -s 9 $DEAMON
	if [ $KERNEL = "2.4" ] 
	then
        	rm -rf /dev/vttyAP*
	fi

}


usage()
{
cat << EOF
usage: $0 options

This script lists helps you manage local advtty service.

OPTIONS:
   -h      Show this message
   -o	   Execute objective:
   		start 	- start advtty local service
		stop 	- stop advtty local service
		restart	- restart advtty local service
		sync	- syncronize advtty service with config
		insert	- insert $DRIVER.ko module
		remove	- remove $DRIVER.ko module
		upgrade - upgrade VCOM to a newer version
   -D     Define options passed to the upgrade service
			-D upgrade_type=stable
				for latest stable release(default)
			-D upgrade_type=development 
				for latest version under R&D
Example:
	$0 -o start
	$0 -o restart
	$0 -o stop
	$0 -o sync
	$0 -o upgrade
	$0 -o upgrade -D upgrade_type=development

EOF
}

while getopts “ho:D:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         o)
             OBJECTIVE=$OPTARG
             ;;
		 D)
		 	UPGRADEOPT+=($OPTARG)
			;;
         ?)
	     usage
             exit
             ;;
     esac
done

case $OBJECTIVE in
	start)
		hasdriver
		if [ $RETURN -eq 1 ]
		then
			echo "starting service...."
			startDeamon
		else
			echo "installing driver & start service..."
			insdriver
			startDeamon
		fi
		exit 0
	;;
	restart)
		hasdriver
		if [ $RETURN -eq 1 ]
		then
			stopService
#			echo "starting service...."
			startDeamon
		else
#			echo "starting service..."
			insdriver
			startDeamon
		fi
		exit 0

	;;
	sync)
		hasdriver
		if [ $RETURN -eq 1 ]
		then
			echo "sychronizing service...."
			syncDeamon
		else
			echo "installing driver & synchronizing service..."
			insdriver
			syncDeamon
		fi
		exit 0
	;;
	stop)
		echo stop
		stopService
		stopDeamon
		exit 0
	;;
	insert)
		insdriver
		exit 0
	;;
	remove)
		stopService
		stopDeamon
		rmdriver
		exit 0
	;;
	upgrade)
		rm -fR ${UPGRADEPATH}
		mkdir -m 660 -p ${UPGRADEPATH}
		tar xjvf ${INSTALLPATH}/makefile.backup.tar.bz2 -C ${UPGRADEPATH}
		make upgrade -C ${UPGRADEPATH} "${UPGRADEOPT[@]}"
		rm -fR ${UPGRADEPATH}
		exit 0
	;;
esac
usage


